// ¿Qué es el principio SOLID?
// SOLID, en pocas palabras, es  un acrónimo que representa cinco principios básicos de la programación orientada a objetos y el diseño.

// Los 5 principios:

// Principio de Única Responsabilidad: un objeto solo debería tener una única responsabilidad.
// Principio Abierto/Cerrado:  las entidades de software deben estar abiertas para su extensión, pero cerradas para su modificación.
// Principio de sustitución de Liskov: los objetos de un programa deberían ser reemplazables por instancias de sus subtipos sin alterar el correcto funcionamiento del programa.
// Principio de Segregación de la Interface: muchas interfaces cliente específicas son mejores que una interfaz de propósito general.
// Principio de Inversión de Dependencia: la noción de que uno debería depender de abstracciones y no depender de concreciones.
